{
 "title": "Deluge",
 "description": "Deluge Dashboard",
 "tags": [
  "prometheus",
  "deluge",
  "torrents"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Torrents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"total\"}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"active\"}"
    }
   ]
  },
  {
   "title": "Queued",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"queued\"}"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"paused\"}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"error\"}"
    }
   ]
  },
  {
   "title": "Deluge Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deluge_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Downloading",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"downloading\"}"
    }
   ]
  },
  {
   "title": "Seeding",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"seeding\"}"
    }
   ]
  },
  {
   "title": "Seeders",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_peer_incoming_connections_total"
    }
   ]
  },
  {
   "title": "Leechers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_peer_num_tcp_peers"
    }
   ]
  },
  {
   "title": "Total download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_net_recv_bytes_total"
    }
   ]
  },
  {
   "title": "Total upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_net_sent_payload_bytes_total"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "deluge_torrent_done_total", "legendFormat": "done" },
    { "expr": "deluge_torrent_uploaded_total" },
    { "expr": "deluge_torrent_size_total" },
    { "expr": "deluge_torrent_num_peers" },
    { "expr": "deluge_torrent_num_seeds" }
   ]
  },
  {
   "title": "Bandwidth Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "deluge_libtorrent_ses_num_outgoing_request_total",
     "legendFormat": "Upload"
    },
    {
     "expr": "deluge_libtorrent_ses_num_incoming_request_total",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Torrent Ratio",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_net_sent_payload_bytes_total",
     "legendFormat": "Upload"
    },
    {
     "expr": "deluge_libtorrent_net_recv_bytes_total",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Labels",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deluge_torrents_by_label", "legendFormat": "{{label}}" }
   ]
  }
 ]
}